#!/bin/bash
#
#<UDF name="scriptversion" Label="Script edition" oneOf="Latest,Development" example="Script version." default="Latest"/>
#<UDF name="url" default="https://github.com/TirsvadCMS-Bashscripts/LinuxServerSetupDefaultConfig/tarball/master" Label="Url link to a your own configuration as a tarball. With strip components 2" example="https://github.com/TirsvadCMS-Bashscripts/LinuxServerSetupDefaultConfig/tarball/master"/>
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u #
exec &> /root/stackscript.log

[ ${SCRIPTVERSION}=="Latest" ] && curl -L https://github.com/TirsvadCMS-Bashscripts/LinuxServerSetup/tarball/master | tar xz -C /root --strip-components 1
[ ${SCRIPTVERSION}=="Development" ] && curl -L https://github.com/linode-scripts/PlaygroundNginxRtmp/tarball/master | tar xz -C /root --strip-components 1

export DEBIAN_FRONTEND=noninteractive

cd /root/LinuxServerSetup/scripts
[ ${URL:-} ] && bash setup.sh --url $URL --strip_components 2 || bash setup.sh